### ISSUE TITLE
Simple requests

### ISSUE THREAD

**Issue by Decopi** [dauphine-dev/drop-feeds#1]
I like your add-on. Thank you!
Please, consider the following requests:

1) A 3-pane view (Source, Title article, View article)

2) Title article pane, showing just a clean list of titles (not rectangles)

3) All title article showed in just 1 pane. Present layout opens a new tab for every source. I have more than 200 RSS sources, so it is unpractical for me to open a tab for each source.

4) More scanner threads to speed up the "check feeds".

Thank you!

PS: For years I used FoxNews (https://addons.mozilla.org/en-US/firefox/addon/newsfox/). Sadly it is legacy, not updated, so not working with FF+57. I believe it was the best RSS reader ever. please, feel free to take a look at FoxNews, who knows you can incorporate good ideas to your excellent add-on.

**Comment by Decopi** [comment]
Hi,

Nice improvements today (version 0.2). Thank you!

Scanner threads are now fast.
And opening all feeds in same tab... perfect!
Thank you again.

It will be great a 3-pane view layout, 3 columns, one for RSS sources, another column for article titles, and the third column for view selected title.

In my opinion your add-on is getting better and better, much more better than other RSS readers, and much more tiny and weight-light.

Congratulations!

**Comment by dauphine-dev** [comment]
Thanks for your feed back
I am working on big code refactory, after that it will be more easy to to what you ask, but I am afraid it will take a while... 
In the mind time I will branch to do some minor fixes on the active version, and publish a new version with fixes on Mozilla addons (coming soon)

**Comment by Decopi** [comment]
@dauphine-dev thanks for the constant upgrades and general progress! I am really enjoying every improvement.

I do realize that all this work demands a lot of effort and time consuming from you. But I can't avoid myself to still anxiously wait for the 3-pane view layout (3 columns, one for RSS sources, another column for article titles, and the third column for view selected title).

Please, don't rush at all, take all the time you need, I already understood that you have other priorities. Again, I just wanted to thank your progress, confirming that I am enjoying and I still waiting for more in the future.

Congrats @dauphine-dev !
