### ISSUE TITLE
[Feature] Mark all as read, and select all flux from website

### ISSUE THREAD

**Issue by Machou** [dauphine-dev/drop-feeds#100]
**ENGLISH**

Hello

I have two small requests that would be really cool to add.

1. Mark all RSS feeds as read directly, instead of marking them one by one, which is daunting and slow. If we have 2-4 RSS feeds, that's good, but if we have about 30, like me, it's not as good: P
2. When you scan a site and find several RSS feeds, you have to add them one by one, it would be nice to be able to select all the RSS feeds you want to add directly.

Regards,
Machou

**_==================================================_**

**FRENCH**

Bonjour

J'ai deux petites demandes qui serai vraiment cool d'ajouter.

1. Marquer tous les flux RSS comme lus directement, au lieu de les marquer un par un, ce qui est rébarbatif et lent. Si on a 2-4 flux RSS, c'est bien, mais si on en a une trentaines, comme moi, c'est moins bien :P
2. Lorsqu'on scan un site et que l'on trouve plusieurs flux RSS, on doit les ajouter un à un, ça serai bien de pouvoir sélectionner tous les flux RSS que l'on souhaite ajouter directement.

Cordialement,
Machou

**Comment by dauphine-dev** [comment]
Hi @Machou 
About 1. :  You can right click on the root folder and select "Mark as read"
About 2. :  I will see what I can do.

**_==================================================_**

**FRENCH**
Bonjour @Machou 
(c'est bien de la partie en anglais de la conversation, comme cela si d'autres se posent les mêmes questions, ils auront les réponses)

A propos de 1. : Il faut faire un clic droit sur le dossier racine et sélectionner "Marquer comme lu"
A propos de 2. : Je vais voir ce que je peux faire.

Merci / Thank you

**Comment by Machou** [comment]
1. Cela implique d'afficher le dossier racine, c'est pour cela qu'un petit bouton serai plus approprié je pense.
2. Merci :)

**Comment by dauphine-dev** [comment]
1. and 2. are done in Drop Feeds 0.9.5rc1.
This version should be on AMO after a week, but you can already install it from GitHub 
https://github.com/dauphine-dev/drop-feeds/releases


**_==================================================_**

**FRENCH**
1. et 2. ont été traité dans Drop Feeds 0.9.5rc1.
Cette version devrait être accessible sur AMO dans une semaine, mais tu peux déjà l'installer à partir de GitHub 
https://github.com/dauphine-dev/drop-feeds/releases
