### ISSUE TITLE
super taf !

### ISSUE THREAD

**Issue by lorenzolamas** [dauphine-dev/drop-feeds#11]
Merci beaucoup , je ne trouvais pas d'alternative à Sage Feed !
Par contre, sauf erreur de ma part, il n'est pas possible de n'afficher les "résultats" que sur la seconde partie de la colonne. (en bas)
Là ils 'affichent en bas mais aussi dans le cadre principal de navigation.

**Comment by dauphine-dev** [comment]
Oui je sais.
C'est prévu pour là 0.7

Merci pour le retour.

N'ésites pas a en faire d'autre, ce sont les retours me permettent d'améliorer Drop Feeds.

Merci.

PS: Si tu vois des fautes de français n'esites pas à faire un pull request sur le fichier fr/messages.json ou à défaut signales les moi.

**Comment by lorenzolamas** [comment]
OK pas de problèmes.
J"ai aussi un truc étrange" sur certain site, au lieu de m'ouvrir la page de la news, ça me demande de telecharger un fichier..

**Comment by dauphine-dev** [comment]
Tu as un exemple, je n'ai jamais eu ça (et j'ai 600 flux..).
Et  quel OS / version de Firefox ?

**Comment by dauphine-dev** [comment]
Pour info la 0.7 vient de  sortir

**Comment by lorenzolamas** [comment]
Windows 10, firefoxe 60.01 64bits
Et le flux rss concerné c'est: http://dreamcast-news.blogspot.com/feeds/posts/default
la 0.7 ne change rien.

**Comment by dauphine-dev** [comment]
Je ne reproduis pas.
mais 
  http://dreamcast-news.blogspot.com/feeds/posts/default
est une redirction vers 
  http://feeds.feedburner.com/DreamcastNews

Peut être que tu as joué avec les options de redirection dans about:config

sinon essaies de t'abonner directement à 
  http://feeds.feedburner.com/DreamcastNews

Tiens moi au courant.

Je vais fermer cette issue (ne pas affichier le flux), car c'est dispo. dans la 0.7.
Si le soucis de 'telechargement de fichier" persiste, ouvre une nouvelle issue.

Merci.
