### ISSUE TITLE
Yay for version 0.99rc

### ISSUE THREAD

**Issue by Judy85** [dauphine-dev/drop-feeds#111]
Please don't forget to change status "experimental" to final. Don't let [them](https://addons.mozilla.org/en-US/firefox/addon/sage-like) steal your thunder! You're so much further ahead already.

**Comment by dauphine-dev** [comment]
Yes the final version will come, and I will change the status to final.
Thank you for your support ;-)

**Comment by dauphine-dev** [comment]
@Judy85 
I have just published 1.0 version remove the "experimental" flag, and ask to Mozilla for extension Drop feeds to be featured. ;-)

**Comment by Judy85** [comment]
Congrats on this great milestone! :-)

    On Monday, April 15, 2019, 4:10:00 PM GMT+2, dauphine-dev <notifications@github.com> wrote:  
 
 
@Judy85
I have just published 1.0 version remove the "experimental" flag, and ask to Mozilla for extension Drop feeds to be featured. ;-)

**Comment by dauphine-dev** [comment]
Thank you :-)
