### ISSUE TITLE
feeds directory tree doesn't display

### ISSUE THREAD

**Issue by free-birds** [dauphine-dev/drop-feeds#112]
feeds directory tree doesn't display in sidebar ,just has a flash,then gone.
i checked the bookmarks ,the drop feeds directory is there with all my subscribed feeds. just can't see from the drop feeds sidebar.
what's wrong?
firefox: 66.0.3 32bit

**Comment by dauphine-dev** [comment]
Hi @free-birds 
I have not ideas what can be wrong.

Please go in Firefox Add-ons menu, then go in Drop feeds preferences,
then on "Advanced" tab, click on "Export every thing..." button and attach the exported file here.
So I will can import your settings and see if I can reproduce/fix the issue.

Too, you can try to start Firefox with a fresh Firefox profile, see [here](https://github.com/dauphine-dev/drop-feeds/wiki/Test-Drop-Feeds-with-a-fresh-profile). If it works with a fresh profile, it can means something is wrong is your current profile, like a settings in about:config, or an other addon not compatible with Drop Feeds, or what ever...

**Comment by Judy85** [comment]
@free-birds 

Maybe you see the same as me which happens occasionally:
![image](https://user-images.githubusercontent.com/33347388/56944781-f9799400-6b24-11e9-9d25-fa7cf5e46e87.png)

Moving the gray bar down for me the feeds become visible again.

**Comment by free-birds** [comment]
@Judy85 thank you! That's the solution.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Apr 30, 2019, 6:51 AM by notifications@github.com:

**Comment by dauphine-dev** [comment]
Yes, @Judy85 thank you.
I close the issue.
