### ISSUE TITLE
Feed deleted from Drop feed bookmarks upon viewing

### ISSUE THREAD

**Issue by kayceejay** [dauphine-dev/drop-feeds#114]
#### System: 
 * Operating System:  Windows 10 1809
 * Firefox version: 66.05 64-bit
 * Drop Feeds version : 1.0

#### Steps to reproduce:
-- Installed Drop Feed (Thank you! Been looking for a Sage replacement!!
-- Populated feed list with one folder "Drop Feeds" and three sub-folders "General Interest" "Tech" and "News"
-- Click on any Drop Feed item under "Tech".

#### What should happen:
Drop Feed bookmark is unchanged, articles display in main screen.

#### What actually happened:
Drop Feed bookmark is deleted, articles display as expected in main screen

![Drop Feed Firefox add on git hub issue 2019-05-08 v02](https://user-images.githubusercontent.com/4838283/57393776-717d3500-7189-11e9-9c08-e9c9deb0b9d9.jpg)

**Comment by kayceejay** [comment]
Not a bug, my  user error.

See toggle button "View only updated feeds".

![updat-tolggle](https://user-images.githubusercontent.com/4838283/57403206-bd86a480-719e-11e9-8b42-9bebd9c107cc.jpg)

**Comment by dauphine-dev** [comment]
Hi @kayceejay 
Glad to know what you have found a solution to your issue (I was afk for a few days)
