### ISSUE TITLE
[Theme edited] Sage SC Dark with light items title

### ISSUE THREAD

**Issue by Judy85** [dauphine-dev/drop-feeds#115]
From theme Sage SC Dark I made items-Title-color a lighter color.
[df-mainTheme-sage_sc_dark.zip](https://github.com/dauphine-dev/drop-feeds/files/3366999/df-mainTheme-sage_sc_dark.zip)

**Comment by dauphine-dev** [comment]
Hi @Judy85 
Thank you.
I don't use this theme, but I can see you have right it is better like this, please if you have other improvements don't hesitate to share them.

I will make a new version 1.0.1 to integrate this change.
