### ISSUE TITLE
[Bug]  Issue on Fedora 31 with Firefox 71

### ISSUE THREAD

**Issue by it1804** [dauphine-dev/drop-feeds#117]
Note: Don't esitate to add screenshots 

#### System: 
 * Operating System:  Fedora 31 (64bit)
 * Firefox version: 71
 * Drop Feeds version : 1.0.2

#### Steps to reproduce:
Clean install or reinstall from Fedora 31 yum repo

#### What actually happened:
about:debugging show console error
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied.

Links marks as unavailable and  dosnt open in tab

#### Addition information:
Firefox 70 work great
Windows 7 and Firefox 71 work great

**Comment by dauphine-dev** [comment]
I have just checked on Firefox 71 and 72, I get no issues.
But I am on Mint 19.2, I will try (not today) to install  Fedora 31 (64bit) in a V.M. with Firefox 71 to see what happens.

**Comment by notsure13** [comment]
Thanks for looking into it. I also have 'that' problem. Since FF71 drop-feeds isn't really doing anything any more. It seems to check feeds in the background, but as soon as you click on anything, nothing happens. I'm on debian unstable amd64.

**Comment by dauphine-dev** [comment]
Now I am reproducing, then now I can look how to fix that.

**Comment by dauphine-dev** [comment]
This error happens because the API to write to local storage is broken.
The issue is describe here:
  https://bugzilla.redhat.com/show_bug.cgi?id=1779570

I will do a fix to avoid DropFeeds crashes, but every things related to local storage writing will not work (like adding new feeds, saving feed status, and so...)

**Comment by it1804** [comment]
Thanks for the link to this bug. Fedora 31 has already assembled a working assembly.
In the assembly firefox-71.0-15.fc31 the drop-feeds addon works fine.

**Comment by dauphine-dev** [comment]
ok thank you for the information,
Anyway I have done the fix to avoid crash in 1.0.3
