### ISSUE TITLE
probleme sur un flux

### ISSUE THREAD

**Issue by lorenzolamas** [dauphine-dev/drop-feeds#12]
J'ai changer l'adresse du flux de "Dreamcast news", avec le lien que tu m'avais donné sur le post précédent et ça ne change rien:

https://prnt.sc/jj67cf

Je n'ai rien bidouillé dans le about:config...

**Comment by dauphine-dev** [comment]
Pour mémoire:
  Lorsque tu tentes d'afficher un flux Firefox te demande de télécherger un fichier

  cf: https://prnt.sc/jj67cf

  le flux concerné est
    http://dreamcast-news.blogspot.com/feeds/posts/default
  qui est une redirction vers
    http://feeds.feedburner.com/DreamcastNews
  Celà se produit entre autre sous Firefox 60.01 64bits / Windows 10

  Pour info j'utlise Linux, je vais voir si je peux tester sous Windows 10 64bit.

English:
  Then the user try to display a feed, Firefox ask to him to download a file.
    See here: https://prnt.sc/jj67cf
  the impacted flux is
    http://dreamcast-news.blogspot.com/feeds/posts/default
  in fact this feed redirect to http://feeds.feedburner.com/DreamcastNews.
  It happens at least with Firefox 60.01 64bits / Windows

**Comment by dauphine-dev** [comment]
Voici le lien vers une vesion beta (future 0.7.5)
Dis moi si tout est ok pour toi merci.
https://we.tl/Wkv5tt1nZl

English:
This a link to a beta version (pre. 0.7.5)
Tell me if every things is ok. Thank you.
https://we.tl/Wkv5tt1nZl

**Comment by lorenzolamas** [comment]
Super! Plus de problème avec cette version pour Dreamcast News =)

**Comment by lorenzolamas** [comment]
OK, lamas.lorenzo [at] free fr

**Comment by dauphine-dev** [comment]
j'ai caviardé ton email ;-)
