### ISSUE TITLE
[Bug] Drop feed does not update

### ISSUE THREAD

**Issue by MikaelBoldt** [dauphine-dev/drop-feeds#122]
Using the latest version of Firefox on my win10 pc. vers. 79.0
Drop Feed updated yesterday. version 1.0.6
#### What should happen:
when pressing the button "Check feed" the feeds with ew content should be highlighted - but nothing happens.
if I click on the feeds individually, the latest feeds are shown. 
#### What actually happened:
nothing
#### Addition information:
none

**Comment by dauphine-dev** [comment]
Hello @MikaelBoldt ,
I don't have this issue. but I know what has been changed and is doing that, then I will undo the change, but please can you share your settings to help me to understand why it is happening for you. To share you settings  in Options/Advanced/Exoprt every thing, and upload the file here.

**Comment by MikaelBoldt** [comment]
Please find the file requested attached
[df-full-export.zip](https://github.com/dauphine-dev/drop-feeds/files/5114889/df-full-export.zip)

**Comment by dauphine-dev** [comment]
Thank you.
Is it working now with version 1.0.7 ?

**Comment by MikaelBoldt** [comment]
The Drop Feed, version 1.07 23. august 2020, is working.
Thank you very much.

**Comment by dauphine-dev** [comment]
Great,
You are welcome :-)
