### ISSUE TITLE
How to delete old rss links

### ISSUE THREAD

**Issue by SteveM2020** [dauphine-dev/drop-feeds#129]
I didn't see anything for deleting old links in the setup. Are these held in a log file that will continue to grow? Are they automatically purged?

**Comment by dauphine-dev** [comment]
Hi @SteveM2020 , 
I am not sure to understand what you ask.

But I will try answer: 
You can delete a feed, by right click on it and then choose "Delete".  There is not log file. Feed link has store in Firefox bookmarks, and states of feeds are store in local storage, when you delete a feed then the link is removed from bookmarks, and the state is remove from the local storage.
