### ISSUE TITLE
Subscribe button does not work after finding a feed via search function

### ISSUE THREAD

**Issue by wberger1** [dauphine-dev/drop-feeds#130]
#### Addition information:
Love Drop Feeds.  It works perfectly on my Win 10 64 bit Home Dell Desktop and my old Win 7 Dell Laptop.  Bpught a  new Dell XPS 15 64 bit laptop with Win 10 Home to replace the old one.  Drop Feeds will not add subscriptions.  It may find a subscription using the search function, but will not add/save it which makes it useless.  Have tried removing and reinstalling.  No change. Same problem on the immediate predecessor to Firefox 88.0 Help?

**Comment by dauphine-dev** [comment]
Hi @wberger1 
Firefox has no more "subscribe" "button" (for what I know), but Drop Feeds, has his own button :
![image](https://user-images.githubusercontent.com/36274213/115959142-f1ce0980-a50a-11eb-8888-6021802aac85.png)
and it works for me.
It should opens a new window to allow you to choose where in Drop Feeds tree put the new feed.

May be you have some options activated, that prevent this window to open ?

**Comment by dauphine-dev** [comment]
And yes there is bug in "Discover Feeds" window, the search never end.
I will try to fix it quickly.

But when you click on the search button, it should open the "Discover Feeds" window, then I still think you have some options preventing windows opening.

**Comment by dauphine-dev** [comment]
"Discover Feeds" window issue has been fixed in Drop Feeds 1.0.10.
I keep open this issue open for a while, to let you see if it has solved your problem.

**Comment by dauphine-dev** [comment]
No new since April, then I assume that it is fixed. You can open it again if you still have the issue.
