### ISSUE TITLE
Feeds all disappeared 

### ISSUE THREAD

**Issue by SteveM2020** [dauphine-dev/drop-feeds#131]
I have the newest Firefox browser and Drop Feeds was updated in June. It's set to automatic updates. Today I clicked on the extension to read my feeds, and they were all gone. Is this something that can be fixed?

**Comment by dauphine-dev** [comment]
Hi SteveM2020,
I am afraid that nothing can be done.

But just in case, go to Settings/Advanced/Export every things
Put the file here
And I look if i can retrieve your feeds.

**Comment by dauphine-dev** [comment]
No news from July then I close this issue
