### ISSUE TITLE
[Bug] Icon and addon itself not appearing on latest Firefox on fresh installation

### ISSUE THREAD

**Issue by defenset** [dauphine-dev/drop-feeds#135]
#### System: 
 * Operating System: Ubuntu  
 * Firefox version: 94
 * Drop Feeds version : 1.0.13

#### Steps to reproduce:
Install addon.
#### What should happen:
Icon should appear on toolbar and on sidebar.
#### What actually happened:
Addon is nowhere to be found.

**Comment by dauphine-dev** [comment]
Hi @defenset 
I have just tested, same OS, same FF version with a fresh user session, I get the Dropfeeds icon.
see in the top right corner in the screen shot below.
![dropfeeds](https://user-images.githubusercontent.com/36274213/141613190-069e6435-585d-499d-abc5-0578748ac0b4.png)

And I like to move it in the left to corner, to get some thing close the old good Sage :
![image](https://user-images.githubusercontent.com/36274213/141613252-ef96b3b8-a4a2-45f2-8e9c-0754d63df5c4.png)

Then for now I close, this issue. But you can still add more information to it, and I may be I will able to help you to get the icon back on your computer.

**Comment by defenset** [comment]
that's strange, I just did it again, and it's not there. Is there any workaround to bring it up ?

**Comment by dauphine-dev** [comment]
Very weird, there is no code here, it defined directly in the manifest.
In the section :
```
"browser_action": {
    "default_icon": "themes/_templates/img/drop-feeds-64.png"
  },
```
from the "manifest.json" file
and the "drop-feeds-64.png" is embed in the xpi extension file, and xpi is more or less a zip file signed by Mozilla, then it should work automatically. May be some kind of authorization is missing because, some settings in your "about:config" ?

I don't know any workaround :-(

**Comment by defenset** [comment]
Ok, I found a solution, I’ve been updating firefox for some time, from version to version and this might have caused the problem, I did **Give Firefox a tune up, refresh firefox**, and all came back to where it suppose to be and working again.

**Comment by dauphine-dev** [comment]
Glad to know, you have found a solution to your problem :-)
