### ISSUE TITLE
Images with enclosure type="image/jpeg" are not shown anymore with 1.0.16

### ISSUE THREAD

**Issue by blumenkohl99** [dauphine-dev/drop-feeds#144]
#### System: 
 * Operating System:  Linux or Windows
 * Firefox version:  110
 * Drop Feeds version : 1.0.16.3

#### Steps to reproduce:
https://www.spiegel.de/schlagzeilen/index.rss

#### What should happen:
Image per feed item should be displayed

#### What actually happened:
No image is shown

#### Addition information:
With 1.0.15 the images are shown. It seems that images provided with "\<enclosure type="image/jpeg" url="<url to jpeg"/\>" are not shown anymore with 1.0.16

**Comment by dauphine-dev** [comment]
Thank you for your report.
It is now fixed in [Drop feeds 1.0.16.4](https://github.com/dauphine-dev/drop-feeds/releases)
