### ISSUE TITLE
Problems with Windows-1251 encoding in RSS feeds

### ISSUE THREAD

**Issue by meganomix** [dauphine-dev/drop-feeds#22]
Hi
It looks like Drop-Feeds is having problems with Windows-1251 encoding in RSS feeds.

For example just a few feeds having Windows-1251 encoding:

http://fanat1k.ru/rss2.php
http://alfabank.ru/_/rss/_rss.html
http://fratria.ru/cgi-bin/MainNews/rss.cgi
http://ss.sport-express.ru/rss/football_news.rss
http://driveroff.net/rss/
http://loginvovchyk.ru/rss.xml
http://www.samlab.ws/rss/
http://www.winstart.ru/rss.xml
https://samsung-fun.ru/cache/rss/news.rss

When you add any of the above to Drop-Feeds you will see a set of unreadable characters (see the attachement)
![- -1](https://user-images.githubusercontent.com/39710214/40627066-4ab2fda2-62c5-11e8-8a51-1e43ff85737d.jpg)

**Comment by thieleke** [comment]
@meganomix - does this text look correct to you?  (from http://ss.sport-express.ru/rss/football_news.rss)

![screen shot 2018-05-28 at 4 51 51 pm](https://user-images.githubusercontent.com/3139346/40630681-298341ee-629a-11e8-8761-e601c5215fdb.png)

**Comment by meganomix** [comment]
This is very strange. When I first clicked http://ss.sport-express.ru/rss/football_news.rss the feed was ok and had charset=UTF-8, but when I clicked one more time then I saw again a set of unreadable characters.
All other above feeds look the same (unreadable). Where's the problem? Never saw this when using Sage. 

Latest Firefox 60.0.1 (64x). No other extensions installed. Windows 10 64x.

**Comment by meganomix** [comment]
Tried to install Drop-Feeds on another PC (newest Dell). The same problem. All the feeds below are unreadable:
http://fanat1k.ru/rss2.php
http://alfabank.ru/_/rss/_rss.html
http://fratria.ru/cgi-bin/MainNews/rss.cgi
http://ss.sport-express.ru/rss/football_news.rss
http://driveroff.net/rss/
http://loginvovchyk.ru/rss.xml
http://www.samlab.ws/rss/
http://www.winstart.ru/rss.xml
https://samsung-fun.ru/cache/rss/news.rss

**Comment by meganomix** [comment]
@thieleke yes the feeds in the screenshots you've sent look OK

**Comment by dauphine-dev** [comment]
@meganomix @thieleke
I have merged thieleke fix.
I have create a test version (0.7.899) available here:
https://we.tl/J5b4tUsnyT
Please tell me it is ok, if yes then I will make it public as 0.7.9
Thank you both :-)

**Comment by meganomix** [comment]
Yes, your test version works OK. All feeds look fine! Thank you!

**Comment by dauphine-dev** [comment]
Then I close this issue and I make this version public ;-)

**Comment by dauphine-dev** [comment]
Hi @meganomix
you seems to be a Russian speaker, are you interesting to translate Drop Feeds to Russian ?

_(I am contacting you here (in this issue thread) because I don't know how to contact you by another way. Github doesn't allow private message)_

**Comment by meganomix** [comment]
Unfortunately no.

ср, 30 мая 2018 г. в 17:09, dauphine-dev <notifications@github.com>:

**Comment by dauphine-dev** [comment]
No problems, 
thank you for the bug report :-)
