### ISSUE TITLE
Prevent loading feed content

### ISSUE THREAD

**Issue by Judy85** [dauphine-dev/drop-feeds#28]
I have Render feeds off. Opening feed https://southfront.org/feed/ I suddenly hear a sound. Testing with Render feeds enabled I see the page opened in "blob:moz-extension://xxx" with lots of pictures and one of the video's that's playing automatically. 

Wouldn't it be possible for sites to publish dangerous content this way?
Can this loading on the background please be prevented at all (performance)?

**Comment by dauphine-dev** [comment]
Hi  Judy85,
Than you for your feedback, 
You have right. Drop Feeds is still in development, this feature is scheduled  for 0.8.x version, see the road map here:
https://github.com/dauphine-dev/drop-feeds/blob/master/road-map

**Comment by Judy85** [comment]
Thanks for the road map! Nice to see this is already addressed by you. Keep up the good work!
