### ISSUE TITLE
Enhance middle-click behavior

### ISSUE THREAD

**Issue by Judy85** [dauphine-dev/drop-feeds#29]
Thanks for adding middle-click mouse button support to open feed items.

Would it be possible to further tweak this behavior, please? I would like to use left-click for opening items in the current tab and middle-click to open items in a new tab preferably in the background. I think it used to work this way in sage++. 

Also, when using the middle-click mouse button to open feed items I've noticed the auto-scroll icon popping up annoyingly when autoscrolling is enabled (option in Firefox general options). With this disabled, the icon does not appear but then I miss auto scroll. Can you do something about this?

**Comment by dauphine-dev** [comment]
I have made fixes for "Auto update interval" and "Enhance middle-click behavior". For "Stop the Check feeds when it's running" I will do that later because it is not easy to do.
  Here this is a test version :
https://we.tl/MXrUqDa3DL
Please can you tell me if every thing is ok for you ?
Thank you.

**Comment by Judy85** [comment]
Yay, the new behavior works perfectly thanks! 

I also noticed you tackled the auto-scroll icon issue on the way as well (for feed items list) 👍

**Comment by Judy85** [comment]
Wanted to let you know that "contents area: open new tab in foreground" makes no difference ticked or unticked.

**Comment by Judy85** [comment]
No problem for me as I only open them on the background. Cheers!

**Comment by dauphine-dev** [comment]
This setting affect only the left click.
With the middle click tabs will be opened always in a new tab in background.

**Comment by Judy85** [comment]
yes, I prefer this thanks!
