### ISSUE TITLE
Stop the Check feeds when it's running

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#30]
From Judy85: https://github.com/dauphine-dev/drop-feeds/issues/27

> Additionally, could you please add a possibility to stop the Check feeds when it's running, maybe by clicking the Check feeds icon itself again?

**Comment by dauphine-dev** [comment]
Because check feed management is asynchronous, it is no easy to do. 
Then I will not do it in 0.7.13, and keep that for later.

**Comment by Judy85** [comment]
Ah I see, for me it was just during testing the auto update issue to not hammer the sites too much. Then also it stops automatically after the timeout period set. If I would choose between the ability to stop a running check or asynchronous I'd go for the latter one.

**Comment by dauphine-dev** [comment]
Any way, you stop the current processing by click the Drop feeds button twice to close and reopen it.
That is make me think may be I can add a reload button in the top menu bar. Do you think that is a good idea ?

**Comment by Judy85** [comment]
> Any way, you stop the current processing by click the Drop feeds button twice to close and reopen it.

Ah, I noticed now. With this, instead I would opt to ask for a delay option to start checking feeds automatically X minutes after starting/opening Drop Feeds. Now with auto update working, I don't want to hammer the sites too much. Twitter RSS has been unavailable for me a couple of times due to exceeding quota limits.

> That is make me think may be I can add a reload button in the top menu bar. Do you think that is a good idea ?

I see no added benefits to the existing Check Feeds button to manually (re)load feeds?

**Comment by dauphine-dev** [comment]
You are right, in a future version I will add a option 
`[x] Check feed on start` (when auto check is set) or some thing like that
and if it is unchecked (and it will be unchecked by default) the 1st check will happens after the check interval delay

**Comment by Judy85** [comment]
Nice, thx! I think Check feed on start deserves an own new issue number ;-)

> I see no added benefits to the existing Check Feeds button to manually (re)load feeds?

I now see what you mean. A Stop Feed Check button which actually stops and starts the extension to do its thing. I think I won't use it much with auto update working, but if you think it adds value to your creation can you make the icons smaller?

**Comment by dauphine-dev** [comment]
Done in 0.8
