### ISSUE TITLE
Shows the same article multiple times with Tom's Hardware RSS feed

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#33]
Issue reported on AMO by Anonymous user 956200:
https://addons.mozilla.org/fr/firefox/addon/drop-feeds/reviews/1137548/
>It doesn't seem to work right with the Tom's Hardware RSS feed. Just shows the same article multiple times. Didn't have that issue with Sage or Brief.

**Comment by Judy85** [comment]
Can you please have a look at for example (at this time of writing):
- https://www.ghacks.net/category/firefox/feed/, feed line18;
- https://www.ghacks.net/feed/, lines 2 and 17;
- https://www.mozilla-nl.org/mozbrowser/forum/feed.php, feed line 1.

These do not show the item number and the items can't be selected. Also automatically mark read do not work for these lines.

It used to be much worse though.
