### ISSUE TITLE
Missing item numbers in items panel

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#34]
From https://github.com/dauphine-dev/drop-feeds/issues/33#issuecomment-396690219
Can you please have a look at for example (at this time of writing):

    https://www.ghacks.net/category/firefox/feed/, feed line18;
    https://www.ghacks.net/feed/, lines 2 and 17;
    https://www.mozilla-nl.org/mozbrowser/forum/feed.php, feed line 1.

These do not show the item number and the items can't be selected. Also automatically mark read do not work for these lines.

It used to be much worse though.

**Comment by dauphine-dev** [comment]
It is fixed on 0.7 git branch. I will for some thing else to make a new version, if in few days nothing come then I will make a new version any way. In the meantime you can use this unofficial version (0.7.13a)
https://we.tl/NGtBvOrYVd

**Comment by Judy85** [comment]
Confirmed fixed in 0.7.13a for examples given, thx!
