### ISSUE TITLE
0.8 Beta

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#46]
### Drop feeds 0.8 beta
Hi to everyone who is watching this repository.
You can download Drop feeds 0.8 beta version here: https://we.tl/KtFoa5nK0f
Please try it, and tell me if you found any issues to fix, or any improvements to do.

Thank you

### Changes log:

- User scripts
- Add 'Run an automatic feed update on start' option
- Rework item tooltips to get something closer to Sage++
- Fix items panel vertical scroll bar
- Drag and drop the feed url in man window
- Stop checking by clicking 'Check feeds' button during checking
- Adding security filter settings (thank to Jeff for starting the work ;-). More security options will come on next versions as schedule in road map.

**Comment by jinkama-san** [comment]
Works nicely so far, thanks!
This feed [http://www.windriver.com/feeds/wrsn.xml](url) shows an exclamation mark (but already did with the 0.7 series). I noticed a few typoes, see the attached patch.

[ompl-to-opml.diff.txt](https://github.com/dauphine-dev/drop-feeds/files/2162553/ompl-to-opml.diff.txt)

**Comment by dauphine-dev** [comment]
Thank you, 
the typoe patch is applied and  windriver.com feed is fixed (in next 0.8 of curse)

**Comment by jinkama-san** [comment]
Another minor fix, some broken feeds miss the mandatory <description> item tag.

[allow-missing-itemDescription.diff.txt](https://github.com/dauphine-dev/drop-feeds/files/2163199/allow-missing-itemDescription.diff.txt)

**Comment by dauphine-dev** [comment]
Thank you, patch applied

**Comment by dauphine-dev** [comment]
Thank you to contributors.

I have put Drop Fees 0.8 on line on AMO

**Comment by takepon1** [comment]
https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf

This feed has an update mark. However, when trying to confirm the item, an error icon appears.

**Comment by dauphine-dev** [comment]
It is because RDF feeds are not supported for now.
I have opened an issue https://github.com/dauphine-dev/drop-feeds/issues/48 for that.

**Comment by takepon1** [comment]
Thank　you
