### ISSUE TITLE
Add RDF feed support

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#48]
From https://github.com/dauphine-dev/drop-feeds/issues/46#issuecomment-402585763:

> https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf
> 
> This feed has an update mark. However, when trying to confirm the item, an error icon appears.

**Comment by dauphine-dev** [comment]
@takepon1 
It is because RDF feeds are not supported for now.
I have take a look to https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf feed, and RDF feed seems to be close to RSS feed. I will look what I can do to support them (at least this one).

I haven't found an example to work on, now I have one, thank you.

**Comment by dauphine-dev** [comment]
It is so close to RSS feeds, it already works.

It works for me with last 0.8 version (and I have tested with 0.7 it works too)

If you want you can go on page: "about:debugging"
Check "Enable add-on debugging"

And in add-on list look for Drop feeds and click on "Debug" link then click "ok" on the pop-up window
then you get a debug console. 
Go on console tab, click on the trash can icon to clear the console, and try to open the rdf feed, and look if you get an error, and tell me.

**Comment by takepon1** [comment]
Thank you. I confirmed that no error occurred.

**Comment by dauphine-dev** [comment]
Then can I close this issue, or I have misunderstood what was the problem ?

**Comment by takepon1** [comment]
You can close this issue. Last 0.8 version can read rdf feed.
