### ISSUE TITLE
Feed item tooltips missing non-ASCII characters

### ISSUE THREAD

**Issue by jinkama-san** [dauphine-dev/drop-feeds#49]
Hi,
since 0.8 the feed item tooltips are missing non-ASCII characters (like umlauts). I believe the replace(/\W/g, ' ' ) in _getItemTooltipText() is too eager or wrong. Removing it brings back the tooltips to normal again.
[backslashW-to-eager.diff.txt](https://github.com/dauphine-dev/drop-feeds/files/2184033/backslashW-to-eager.diff.txt)

**Comment by dauphine-dev** [comment]
Fixed in 0.8.2b.
I have changed replace(/\W/g, ' ' ) to replace(/\c/g, ' ' )

Thank you to reported and point the code line issue :-)

**Comment by jinkama-san** [comment]
Thanks, 0.8.2b works fine again. But maybe /\c/ does not do what you expect according to [regex101](https://regex101.com/) in javascript mode. I think you maybe want to use /[\x01-\x1f]/ to capture all control characters?

**Comment by dauphine-dev** [comment]
Ok thank you, I have made the change, it is available in 0.8.2d
