### ISSUE TITLE
Discover feeds button does not work on linux

### ISSUE THREAD

**Issue by DSpammy** [dauphine-dev/drop-feeds#50]
Hi,

I'm trying to make work Drop feeds on my Linux. (I was stucked to FF56 a long time ago because of Sage feeds but I'm trying to step forward.) My problem is that Discover feeds button does not work at all. It stops at the stage on the screenshot below and it is not possible to do other than close the window via clicking x on the upper right corner.

![screenshot_2018-07-23_17-05-45](https://user-images.githubusercontent.com/6402834/43086587-03392dc0-8e9e-11e8-96d5-a616938a5127.png)

The only method I could use to register a feed was the opml import but that is not so elegant...

Attila

ps: Hopefully we will have a great extension shortly.

**Comment by dauphine-dev** [comment]
Thank you to report this issue.
It is fixed in 0.8.2e

**Comment by dauphine-dev** [comment]
![43086587-03392dc0-8e9e-11e8-96d5-a616938a5127](https://user-images.githubusercontent.com/36274213/43101561-fc4fcb10-8ec8-11e8-8c1d-0ba9548d7fbe.png)

To subscribe to this site, you don't need to use "Discover feeds" feature you can click on the "Go to the subscription page" button (see in red circle on the upper right) then you will get the subscription page and then you can click on the "Subscription" button ![subscribe-add](https://user-images.githubusercontent.com/36274213/43101848-b14e72f0-8ec9-11e8-85d7-a43b825f2972.png) (still on the upper right) to subscribe.

The "Discover feed" feature is useful when a site doesn't expose feeds, then  "Discover feed" feature tries to discover them but it can take a while...

**Comment by DSpammy** [comment]
Great, it works! Thank you. Firefox's own subscription dialog appeared on the subscription page and I didn't notice that the icon changed and didn't try use it. :(
