### ISSUE TITLE
wikimedia Special:RecentChanges feeds sometimes cause "SyntaxError: unterminated character class"

### ISSUE THREAD

**Issue by jinkama-san** [dauphine-dev/drop-feeds#58]
Hi,

this happens when the Special:RecentChanges RSS feed (Atom or RSS doesn't matter) creates stuff like that (copied from the "text" variable in _applySecurityFilters()):
     <del class=\"diffchange diffchange-inline\"><[[User:MySelf|ME]]-assumption>''</del>

The attached patch uses TextTools.escapeRegExp() to fix the syntax error, but I'm unsure if it is fully correct.

[escapeTagsForRegEx.diff.txt](https://github.com/dauphine-dev/drop-feeds/files/2415516/escapeTagsForRegEx.diff.txt)

**Comment by dauphine-dev** [comment]
Hi @jinkama-san 
Do you have an example of feed with this issue to make test/debug ?

**Comment by jinkama-san** [comment]
Unfortunately it happened on an inhouse wiki, so there is no external access. I tried to find something on the web but didn't succeed :-(. I'll be on vacation now, but I will try more when I come back.

**Comment by dauphine-dev** [comment]
Ok
any way, I will apply the patch.
But if it is cause issues for other feeds I will rollback it and will look with you how to fix your issue.

**Comment by dauphine-dev** [comment]
Hi @jinkama-san 
I have included the patch in Drop Feed 0.8.5d (available on [AMO](https://addons.mozilla.org/fr/firefox/addon/drop-feeds/) and [Git HUB](https://github.com/dauphine-dev/drop-feeds/releases/tag/0.8.5d))
