### ISSUE TITLE
[Feature request] Option to open item links from a render page in a new tab

### ISSUE THREAD

**Issue by StanGets** [dauphine-dev/drop-feeds#63]
Hi,

Running flawlessly _Drop Feeds_ 0.8.6 / _Firefox_ 63.0 (x64) / _Windows 7_ (x64)

I miss the option to open the links of a RSS in New tab. I'm not referring to DropFeeds' option _Contents area / Always open new tab_ but to how the links on the very tab are opened. At this time I have to either middle-click on the link or right-click and choose '_Open in New tab_'

As you see this is truly a minor feature request yet a valid enhancement IMO.

Thanks!

**Side-note** : I've been a user of the _Feedbro_ Webextension for some time and if I decided to switch to _Drop Feeds_ it is for two reasons:

1- Before _Feedbro_, that is as long as legacy add-ons where available (pre-FF57) I had managed RSS feeds with the excellent _Sage++ (Higmmer's Edition) by Higmmer_ add-on. Indeed _Drop Feeds_ ports that add-on to its Webextension availability in a faithful way (even if it is an independent Webextension of its own).

2- I've noticed with _Feedbro_ as well as with _Drop Feeds_ that updating feeds would create cookies from called sites that decide to associate a cookie with the RSS feed withdraw. These cookies, because created via a Webextension, cannot be removed by an extension such as _ForgetMeNot_ which doesn't even see them, they are written here as session-only cookies (not sure if they'd be session-only if I hadn't session-only as default for cookies) and get removed accordingly on Firefox exit.

From there on there is a work-around which is possible with _Drop Feeds_ but not with _Feedbro_, which is to set the extension's UUID ( moz-extension://.... ) as blocked in Firefox's _Options / Privacy & Security / Cookies and Site Data / Exceptions_.

This cannot work with _Feedbro_ because _Feedbro_ stores data in its IndexedDB dedicated folder and that blocking an extension's cookies blocks its access to its IndexedDB

But this is possible with _Drop Feeds_ because _Drop Feeds_ does not use IndexedDB ...

Sorry for this lengthy development, I think it may interest some users.

**Comment by dauphine-dev** [comment]
Hi @StanGets 
I am not sure to understood what you want (I am not English native then some time I misunderstand...).
Like you said to open a feed in a new tab :
 -  there is an option "Contents area / Always open new tab"n it works with the left click
 - you can right-click and use "Open" option
 - you can use the middle click

Then you want use ????? to  open a feed in a new tab ?

Note:
Thank you for the lengthy development, I will make a wiki page to add the tip about cookies :-)

**Comment by StanGets** [comment]
Hi @dauphine-dev , English is not my mother-tongue as well :=) Herewith a screenshot example:
![ok](https://user-images.githubusercontent.com/42912760/47666939-0da7fd00-dba5-11e8-986d-306898ef8880.jpg)

Once on Drop Feeds' withdrawn RSS feed I'd wish the option to have the links open in a new tab... do you see what I mean? i'm not even sure i'd express myself better in French, lol!

**Comment by dauphine-dev** [comment]
Ok great, I get it now.

I will add that on 0.9 it should be the next version (coming soon) , expect if I have to do an hot fix on the 0.8 branch.

(I can see that you speak french, like as me)

**Comment by StanGets** [comment]
Dauphine/é is so French!
Thanks!

**Comment by dauphine-dev** [comment]
lol, you are welcome.

I have implemented this feature in Drop feeds 0.9beta7. If you want you can start to use it right now, by installing Drop feeds 0.9beta7 available [here](https://github.com/dauphine-dev/drop-feeds/releases).

To enable the feature you have to set the option "Content area / Open items on new tab". It will impact only feeds render after you will have set the option (no effects on already opened feeds).

Have fun with it :-)

**Comment by StanGets** [comment]
@dauphine-dev I'm encountering an issue with Drop Feeds 0.9beta7.
My _Drop Feeds_ folder has 5 sub-folders of which the first only was made available.

**Comment by dauphine-dev** [comment]
Weird, I have 42 folders, and there are all available.

It you have no confidential info in your feeds, do you agree to send me an OPML export of your feeds at dauphinedev[at]serre-fr.org ?
I will do some tests and do a fix. Do you have the option "Do not display the root folder" checked ?

**Comment by dauphine-dev** [comment]
Great, I have received your OPML file, I will look to do a fix, thank you.

**Comment by dauphine-dev** [comment]
I have made a fix, now it should be work with Drop feeds 0.9beta8 available [here](https://github.com/dauphine-dev/drop-feeds/releases)

**Comment by StanGets** [comment]
@dauphine-dev I've just installed **_Drop Feeds 0.9beta8_**

1- The missing folders issue has vanished : they're all available;
2- The new _Contents Area / Open items on new tab_ (checked) doesn't work on first click (which opens in same tab), but re-opening the render page or opening a new one right after works. Works as long as the sidebar remains opened on 'Drop Feeds' : if I switch to, i.e. Bookmarks and return to 'Drop Feeds' same problem with first click on render page ...
3- _Items / Feed item list_ (checked) : the height of the feed item list is not preserved.

**Comment by dauphine-dev** [comment]
Ok, thank you for the beta testing.
I will fix that.

**Comment by dauphine-dev** [comment]
> 1- The missing folders issue has vanished : they're all available;

=> Great, thank you for the feed back

> 2- The new Contents Area / Open items on new tab (checked) doesn't work on first click (which opens in same tab), but re-opening the render page or opening a new one right after works. Works as long as the sidebar remains opened on 'Drop Feeds' : if I switch to, i.e. Bookmarks and return to 'Drop Feeds' same problem with first click on render page ...

=> It is normal on 1st time that doesn't work with already  opened render pages. But it was an issue after close/reopen Drop Feeds, it is fixed in 0.9beta9.

>3- Items / Feed item list (checked) : the height of the feed item list is not preserved.

=> it is fixed in 0.9beta9.

0.9beta9 is available [here](https://github.com/dauphine-dev/drop-feeds/releases) as usual.

**Comment by StanGets** [comment]
I just installed Drop Feeds 0.9beta9, searched unsuccessfully for issues, I really searched, thoroughly, but couldn't find any. So I think I'll keep it.
Lol.
Nice work, @dauphine-dev , running smooth!

**Comment by dauphine-dev** [comment]
De rien / you are welcome :-)
