### ISSUE TITLE
[Feature request] Create a dark theme

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#65]
Create a dark theme.

_Feature requested in user review on AMO ([here](https://addons.mozilla.org/fr/firefox/addon/drop-feeds/reviews/1222108/))_

**Comment by dauphine-dev** [comment]
Hi @thieleke 
I have totally reworked theme management in Drop Feeds,
now :
 - main theme (side bar and dialogs)
 - render template (element disposition in render tab)
 - render theme (mainly colors in render)

are 3 independents things

Then now it doesn't any sens to call your theme "Sage Single Column". 
Install [Drop Feeds 0.9.1rc](https://github.com/dauphine-dev/drop-feeds/releases) and look at the tab "Theme" on option page, you will understand. 
I have thought  to rename it "Jeff", what do think about it ?

**Comment by thieleke** [comment]
@dauphine-dev - Maybe just rename it to "Sage SC"?

**Comment by dauphine-dev** [comment]
Ok I will do that.

Thank you.

**Comment by dauphine-dev** [comment]
Dark themes are available in 0.9.1
