### ISSUE TITLE
Help wanted for 0.9 translation

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#66]
@takepon1 , @yfdyh000, @itsBeen, @ any one want to translate to a new language
Hi guys !
Please can you translate locale from 0.9 branch.
If every things is ok then, a new Drop Feeds version 0.9 will come after the translation.
 
0.9beta9 is available [here](https://github.com/dauphine-dev/drop-feeds/releases) and to help you to translate I have created a file named '[to-translate](https://github.com/dauphine-dev/drop-feeds/blob/0.9/to-translate)' with the list of items to translate.

Thank you !
dauphine-dev

**Comment by dauphine-dev** [comment]
No news....
I will delivery Drop feeds  0.9 without translations for now.
I will do an update to integrate translations when they will available ;-)

**Comment by dauphine-dev** [comment]
Thank you for your help but I am french, then I do the translation myself. But if you see any texts can be improved (or typo) don't hesitate to tell me. Merci bien ;-)

The same for the english version to any one who is reading this, my english is not very good, then if you see any texts can be improved (or typo) don't hesitate to tell me.

**Comment by dauphine-dev** [comment]
Now 0.9.1rc is available [here](https://github.com/dauphine-dev/drop-feeds/releases) and to help you to translate I have created a file named '[to-translate](https://github.com/dauphine-dev/drop-feeds/blob/0.9.1/to-translate)' with the list of items to translate.

**Comment by Judy85** [comment]
For starters here goes. I've not tested this as I don't use Dutch locale, I might have missed some contexts.

0.9;38;sbFilter;Filter;in de zijbalk topmenu;n/a
0.9;41;sbFilterClearButton;Opheffen filter;op filterbalk;n/a
0.9;158;subWindowCloseError;Drop feeds kan het venster niet sluiten, sluit het handmatig.;in het abonneervenster (fout alleen zichtbaar tijdens sluiten van het venster);n/a
0.9;305;optItemNewTab;Items openen middels nieuwe tag;in opties / inhoudsoverzicht;n/a

0.9.1;230;optTheme;Thema;in opties / thema tabtitel;n/a
0.9.1;245;optSelectMainTheme;Selecteer hoofdthema;in opties / thema;was geüpdatet van 'optSelectTheme:Selecteer thema' naar 'optSelectMainTheme:Selecteer hoofdthema'
0.9.1;248;optSelectRenderTemplate;Selecteer weergavesjabloon;in opties / thema;n/a
0.9.1;251;optSelectRenderTheme;Selecteer weergavesjabloon thema;in opties / thema;n/a
0.9.1;305;optFeedItemRenderInSidebar;Geef het geselecteerde item in de zijbalk weer;in opties / Items;n/a

**Comment by anauta** [comment]
I just discovered this add-on. While considering its use I translated these lines into spanish:

0.9 -> las siguientes líneas son válidas para esta versión (algunas cosas, como números de línea, pueden cambiar en versiones futuras)
0.9;38;sbFilter;Filter;en el menú superior de la barra lateral;n/a
0.9;41;sbFilterClearButton;Borrar filtro;en la barra de filtro;n/a
0.9;158;subWindowCloseError;Drop Feeds no ha podido cerrar la ventana, ciérrela manualmente.;en la ventana de suscripción (pero visible solo en el error de cierre de la ventana);n/a
0.9;305;optItemNewTab;Abrir elementos en una etiqueta nueva;en el área de opciones / contenido;n/a

0.9.1 -> las siguientes líneas son válidas para esta versión (algunas cosas, como números de línea, pueden cambiar en versiones futuras)
0.9.1;230;optTheme;Tema;en opciones / título de la pestaña de tema;n/a
0.9.1;245;optSelectMainTheme;Seleccionar tema principal; en opciones / tema; se actualizó de 'optSelectTheme:Seleccionar tema' a 'optSelectMainTheme:Seleccionar tema principal'
0.9.1;248;optSelectRenderTemplate;Seleccione la plantilla de la pestaña de procesamiento; en opciones / tema;n/a

**Comment by dauphine-dev** [comment]
@Judy85, @anauta 
Thank you for contributions,
but this thread is made for already existing translation. The file 'to-translate' list what is new or has changed.
To do a new translation you to translate the entire file [messages.json](https://github.com/dauphine-dev/drop-feeds/blob/master/_locales/en/messages.json)

I close this issue, and I will create a clearest new one .

**Comment by dauphine-dev** [comment]
@takepon1 , @yfdyh000, @itsBeen, @Judy85, @anauta 
I have just created a new and more detailed translation guide [here](https://github.com/dauphine-dev/drop-feeds/issues/75)
