### ISSUE TITLE
rearranging the UI, feed display

### ISSUE THREAD

**Issue by atomGit** [dauphine-dev/drop-feeds#69]
given that DF displays feed content in the main browser view port, i wonder why it's useful to display the feed list in the sidebar?

this may be beyond the goals of the developer, but personally i am very much seeking a WebExt feed reader similar to the popular and well liked Newsfox - a traditional 3 pane display with feeds on the left, headlines on the top-right and article content on the bottom-right

in my opinion this is a very efficient way of reading feeds in that it avoids a lot of extra scrolling through content you don't care about because feed content is only displayed when a headline is clicked

also Newsfox was able to load all headlines from a feed group (folder) and i miss the site icons as well

**Comment by dauphine-dev** [comment]
Hi @atomGit
Welcome !
You are the one has post this [review](https://addons.mozilla.org/fr/firefox/addon/drop-feeds/reviews/1222108/) ?

About the 3rd layout a issue is already open [here](https://github.com/dauphine-dev/drop-feeds/issues/64).

What ever I am working on the 3rd panel. I have tried to install Newsfox, but it is not any more compatible with FF57+, and it has failed to be installed on my FF56 (I haven't investigate why...)

See commits  on 0.9.1 branch, you can event play with the development version by cloning this repo and open it as a temporary add-on, may be it better if you do that on a secondary Firefox session or on other Firefox installation (like Firefox Developer).
As soon I get some thing acceptable (I am close...) I will make an new alpha version (alpha4) [here](https://github.com/dauphine-dev/drop-feeds/releases) with the 3rd panel, then it will be easier to install/test/use. Then you will can tell to me if it is matches with you expectations.

**Comment by atomGit** [comment]
i didn't post that review, but it's nice to see someone else suggesting the 3-pane layout :)

i also missed the existing issue you pointed out - sorry about that

**Comment by dauphine-dev** [comment]
No problems :-)

I will close this one, and merge issues.
