### ISSUE TITLE
0.9.1 - RSS feeds without pubDate show as "null"

### ISSUE THREAD

**Issue by thieleke** [dauphine-dev/drop-feeds#71]
I believe this is new in 0.9.1, although I might not have noticed it in earlier versions.  RSS feeds which don't have the item/pubDate element show up as "null" instead of an empty string.

Example: https://apod.nasa.gov/apod.rss

![screen shot 2018-11-27 at 8 36 50 am](https://user-images.githubusercontent.com/3139346/49088905-f437b680-f21f-11e8-8e33-7640dee3d11b.png)

**Comment by dauphine-dev** [comment]
I have just fix it in 0.9.1a

**Comment by thieleke** [comment]
Thanks for the quick response - I see this fixed in 0.9.1a
