### ISSUE TITLE
The "traditional" 2-row layout doesn't work anymore in 0.9.1

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#72]
I tried fiddling with the various options, but the only thing that works at all is to enable the third row ("render selected item..."), then click on an entry, then go to the render row and click on the entry again; that will open the entry in the main window. 

If I uncheck "render selected item", then nothing happens at all when clicking on the item. However, I'm expecting the item to open in the main window, as version 0.9a did. I'm downgrading to 0.9a for now...

_Originally posted by @fcktrmp in https://github.com/dauphine-dev/drop-feeds/issues/70#issuecomment-442461568_

**Comment by dauphine-dev** [comment]
@fcktrmp 
> Oops... yeah, maybe I should have created a separate issue right away. Anyway, thanks for looking into it! :)

No problem, I will try to do a quick fix, thank you for report this issue (personally I use only one row and render view... But I have tested of curse with 2 rows and 3rd rows, but It seems I missed some thing...)

**Comment by dauphine-dev** [comment]
It is fixed in 0.9.1b.

**Comment by fcktrmp** [comment]
I can confirm it works now, thanks for the ultra-fast reaction!

**Comment by dauphine-dev** [comment]
You are welcome :-)

**Comment by dauphine-dev** [comment]
Note: It was working, but Drop Feeds need to be close and reopen to make the option take effect.
It comes from a very old bug, but it has no visible effect until now...

**Comment by dauphine-dev** [comment]
oops like the other, I reopen it, then any one with 0.9.1/0.9.1a can see an update to 0.9.1b fix this bug, I will close it later.
