### ISSUE TITLE
Translation update for 0.9.2

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#80]
@takepon1, @yfdyh000, @itsBeen , @carlfranz , @Judy85, @anauta 
Hi Translators !

You can start to update the translation for 0.9.2 (strings shouldn't change until the final version).
All changes are available in 'to-translate' file in the root folder.

Thank you :-)

(Wiki:  [Drop Feeds translation main page](https://github.com/dauphine-dev/drop-feeds/wiki/Drop-Feeds-translation-main-page))

Edit:
Italian, and Japanese  updates are merged

**Comment by carlfranz** [comment]
I think mines are fine. I've all the string listed already done on `master` branch. Branche `origin/0.9` does not have italian translation, should I copy the file there too?

**Comment by dauphine-dev** [comment]
The translation update concerns the 0.9.2 branch, then I have added all entries for all languages but in English, then you have to translate them and commit them 0.9.2.

About 0.9, it is old branch before Italian has been added, then is normal that there isn't Italian. 
Then actual one in production is 0.9.1, and it has Italian.

**Comment by Judy85** [comment]
Dutch/nl translations for 0.9.2
[messages.zip](https://github.com/dauphine-dev/drop-feeds/files/2650599/messages.zip)

**Comment by dauphine-dev** [comment]
@Judy85 Thank you !
I have just commit it on 0.9.2

**Comment by dauphine-dev** [comment]
0.9.2 is production, I will add missing translations when they will come, in the meantime I close this issue.
