### ISSUE TITLE
0.9.2rc2 general feedback

### ISSUE THREAD

**Issue by atomGit** [dauphine-dev/drop-feeds#84]
hi dd :)

the UI works much better in general - the css needs work, but that's not a problem

the following are just observations and suggestions...

**render panel - unified feed display** - currently there is no way to identify the source of the feeds

**render panel** - column header (title, visited, date) - columns should be resizable and there should be no wrapped text (tool-tips can be used for long items) - this keeps the list uniform and compact - user should be able to choose what columns they want to display

**-or-** (and i think this is much better idea)...

you could dump the columns completely and display all feeds on 2 lines like [Feedbro](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/) does - this is more modern and 'material' in design and it leaves plenty of room to display headlines and feed metadata (source, author, date, age)

**date format** - should be a setting to specify format, perhaps just a combination control with couple predetermined formats (31-12-9999 | 31-Dec-9999 | 31-Dec | Dec. 31 1999 | Dec. 31 | Sun., Dec. 31) - feed publish times could be added to these (12:60:60, etc.)

**sidebar empty space?** - below the toolbar at the top of the sidebar there is another blank row - does that get used for anything?

**context menus** - context menus for the sidebar should close if the sidebar loses keyboard focus 

**discover feeds** - not sure what this is supposed to do, but in my case a new window opens with a status bar and the process never seems to complete

**Comment by atomGit** [comment]
> date format - should be a setting to specify format, perhaps just a combination control with couple predetermined formats (31-12-9999 | 31-Dec-9999 | 31-Dec | Dec. 31 1999 | Dec. 31 | Sun., Dec. 31) - feed publish times could be added to these (12:60:60, etc.)

[see here](https://i.imgtc.com/0qxRHiG.png)

**Comment by dauphine-dev** [comment]
ha ok, it is the status bar.
It is used for displaying messages (like feeds updating, feed received, etc..)

**Comment by dauphine-dev** [comment]
Issues has been created https://github.com/dauphine-dev/drop-feeds/issues/85, https://github.com/dauphine-dev/drop-feeds/issues/86, https://github.com/dauphine-dev/drop-feeds/issues/87
