### ISSUE TITLE
render panel - alternate display

### ISSUE THREAD

**Issue by atomGit** [dauphine-dev/drop-feeds#85]
suggest to dump the columns completely and display all feeds on 2 lines like [Feedbro](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/) does - this is more modern and 'material' in design and it leaves plenty of room to display headlines and feed metadata (source, author, date, age)

> About render panel I choose the second option and it will be a new render template (may be named AtomGit ???)

i'm not asking for credit, but if you want to do that you can use '12bytes.org' if you want

**Comment by dauphine-dev** [comment]
Hi @atomGit 
in 0.9.7, now you can do your own display designed, by exporting theme, modify it and import it
