### ISSUE TITLE
feed discovery - alternate method?

### ISSUE THREAD

**Issue by atomGit** [dauphine-dev/drop-feeds#86]
> discover feeds is supposed to explored the current page to found no declared rss links (rss link should be declared in the <head> section, but some time there are some links to rss hide in the page not declared in the <head> section, then discover feeds opens links in the page and try to parse them as a feeds and if it success then it was an hidden feed link, at the end the process discover feeds displays a list of all feeds available in the page and then you can subscribe to then. But it can take a while if there are many links in the pages...

ok, that explains why it never completed for me i guess - the page that was open when i clicked the discover feeds icon was the feed render page :)

i'm guessing that you probably have a lot of code for discovering feeds - to parse the head, then all links, plus to determine if the XML is actually a feed, etc. - i don't know if this alternative will help you, but have a look [here](https://12bytes.org/articles/tech/how-to-access-rss-feeds)

**Comment by dauphine-dev** [comment]
It was bugged, now it is fixed in 0.9.2 final

![image](https://user-images.githubusercontent.com/36274213/49599396-3203b000-f981-11e8-89f9-9c16869b3eec.png)

To subscribe use the buttons with a red circles in the above picture.
Discover feeds, it is for discover hidden feeds.

**Comment by dauphine-dev** [comment]
It has been fixed in 0.9.2
