### ISSUE TITLE
[feature] date format options

### ISSUE THREAD

**Issue by atomGit** [dauphine-dev/drop-feeds#87]
be nice to be able to specify format, perhaps just a combination control with couple predetermined formats (31-12-9999 | 31-Dec-9999 | 31-Dec | Dec. 31 1999 | Dec. 31 | Sun., Dec. 31) - feed publish times could be added to these (12:60:60, etc.)

**Comment by dauphine-dev** [comment]
Done in 0.9.3 (but not exactly like as describe upper ;-) )
