### ISSUE TITLE
Crash when sidebar shown and page source code opened

### ISSUE THREAD

**Issue by MinIsMin** [dauphine-dev/drop-feeds#88]
#### System:
Ubuntu 18.10 - Firefox 64.0

#### Steps to reproduce:
- Have Drop Feeds sidebar opened
- Open the page source code of any page (Crtl + U or from right click menu)

#### What should happen:
Firefox should display the page source code without crashing

#### What actually happened:
Milliseconds after the page source code is displayed, Firefox crashes

#### More info:
It only happens with the Drop Feeds sidebar opened, with every other sidebar it works fine
Tested with a complete new profile without other addons

**Comment by dauphine-dev** [comment]
Hi @MinIsMin 
Thank you to report this issue.
It is very well documented :+1: 

I have just done a fix, it is available an on AMO version 0.9.2b

**Comment by MinIsMin** [comment]
Thanks for the quick fix, it works now.
