### ISSUE TITLE
Automatic update not working

### ISSUE THREAD

**Issue by runetek2** [dauphine-dev/drop-feeds#89]
Hello!
good addon and replacement for Sage, just automatic update is not working it seems. Firefox 64 with newest version of Drop Feeds, "Update Checker" settings section set Timeout 60s, Automatic feeds updates every 10 minutes, all the rest is checked.

Yet even overnight or at anytime, nothing is updated and no any new feeds are marked; when I click on Check feeds manually, it's updated correctly.

Not sure what to do with that : (.
Thank you!

**Comment by dauphine-dev** [comment]
Hi @runetek2 
I have just tested, and it has worked for me, with check every 5min.

Can you test with a fresh profile :
 - from command line run firefox -P
 - click on "Create profile", then "next"
 - enter a profile name, for example "test", and click "Finish"
 - select the created profile and click "Start Firefox"
 - Install "Drop Feeds", and test if automatic update works

**Comment by runetek2** [comment]
Did everything exactly step by step, but luck - it's just "dead" icon without any changes

or notifications - yet when I click on refresh manually, it's working perfectly...

 

Thank you,

Milo

**Comment by dauphine-dev** [comment]
What is your OS ? Your locale settings for Firefox ? Any other useful information ?

Go in about:debugging, and click on Drop Feeds "Debug" button.
![image](https://user-images.githubusercontent.com/36274213/50216178-644fdd00-0385-11e9-9066-d7de42128297.png)


In Debug view, Console tab, click on the Clean icon
![image](https://user-images.githubusercontent.com/36274213/50216259-8d706d80-0385-11e9-8269-16145c54b30b.png)
Activate automatic update every 1 min (will be red, but it doen't matter)
Wait for a few minutes, and copy console messages (if they exist) here.

Thank you

**Comment by runetek2** [comment]
Got this info:

 

TypeError: can't access dead object

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

 

From some reason, now updated worked! Yet there is no any small number of new/unreaded feeds on the green drop icon and I must click on it and see bold title.

 

Thank you for your time.

**Comment by dauphine-dev** [comment]
Ok
Then it looks like more a display issue of updated feeds, may be it can be related to a theme. 
Which Drop Feeds main theme you are using ?
Do use a Firefox theme (if yes which one ?) ?

**Comment by runetek2** [comment]
OK, I tried Legacy theme and also Sage SC theme, same in both cases.

 

Firefox theme no, just default light one.

 

Interesting fact is that when I click on green drop button and don't click on refresh, it's refreshed/updated correctly,

but when is the panel with Drop Feeds closed (and only drop icon is present in bookmarks bar), nothing is updated...

**Comment by dauphine-dev** [comment]
Yes Drop Feed need to be loaded (side panel opened) to have automatics update works.

But I will try to think if I can make it work even when the side panel is closed for a next version. For now I close this issue.
